## DATA EXPLORATION & PREPARATION


### part a


In [1]:
import pandas as pd
import os
DATASET_PATH = os.path.join("datasets", "assignment1")
if not os.path.isdir(DATASET_PATH):
    os.makedirs(DATASET_PATH) #if there is no DATASET_PATH this code creates it.
csv_path_train = os.path.join(DATASET_PATH, "train.csv") #data extracting path (datasets/assignment1/train.csv)
df=pd.read_csv(csv_path_train) #for reading data

In [2]:
train_x_a=pd.read_csv(csv_path_train,usecols=range(25)) #for using only 25 columns not SalePrice column
train_y=pd.read_csv(csv_path_train)
train_y=pd.Series(train_y.values[:, -1], name=train_y.columns[-1]) #it contains only SalePrice column

In [3]:
train_x_a.head(2)

MSSubClass  LotFrontage  LotArea Street  OverallQual  OverallCond  \
0          60         65.0     8450   Pave            7            5   
1          20         80.0     9600   Pave            6            8   

   MasVnrArea  BsmtFinSF1  BsmtUnfSF  TotalBsmtSF   ...    BsmtHalfBath  \
0       196.0         706        150          856   ...               0   
1         0.0         978        284         1262   ...               1   

   FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  \
0         2         1             3             1             8           0   
1         2         0             3             1             6           1   

   GarageCars  GarageArea  MoSold  
0           2         548       2  
1           2         460       5  

[2 rows x 25 columns]

In [4]:
train_y.head(2)

0    208500
1    181500
Name: SalePrice, dtype: object

### part b

In [5]:
nan_columns=[df.columns[df.isnull().any()]] #for finding NaN columns
train_x_b=df.fillna(df["LotFrontage"].median()) # writing median of LotFrontage column instead of NaN values


In [6]:
print list(nan_columns)

[Index([u'LotFrontage', u'MasVnrArea'], dtype='object')]


In [7]:
train_x_b.head(2)

MSSubClass  LotFrontage  LotArea Street  OverallQual  OverallCond  \
0          60         65.0     8450   Pave            7            5   
1          20         80.0     9600   Pave            6            8   

   MasVnrArea  BsmtFinSF1  BsmtUnfSF  TotalBsmtSF    ...      FullBath  \
0       196.0         706        150          856    ...             2   
1         0.0         978        284         1262    ...             2   

   HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  \
0         1             3             1             8           0           2   
1         0             3             1             6           1           2   

   GarageArea  MoSold  SalePrice  
0         548       2     208500  
1         460       5     181500  

[2 rows x 26 columns]

In [8]:
train_y=train_y.dropna() #for dropping NaN values
train_x_a=train_x_a.dropna()

### part c

In [9]:
categorical_columns =[(df == "Pave").idxmax(axis=1)[0]] #categorical_columns variable contains column name that includes strings 

In [10]:
print categorical_columns

['Street']


### part d

In [11]:
one_hot=pd.get_dummies(train_x_b["Street"]) #get_dummies function works for one hot encoding.
train_x_b=train_x_b.drop("Street",axis=1) #dropping Street column from train_x_b
train_x_b=train_x_b.drop("SalePrice",axis=1) #dropping SalePrice column from train_x_b
train_x_d=train_x_b.join(one_hot) #adding one hot columns into train_x_d

In [12]:
train_x_d.head(2)

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  MasVnrArea  \
0          60         65.0     8450            7            5       196.0   
1          20         80.0     9600            6            8         0.0   

   BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF  ...   HalfBath  BedroomAbvGr  \
0         706        150          856       856  ...          1             3   
1         978        284         1262      1262  ...          0             3   

   KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  GarageArea  MoSold  \
0             1             8           0           2         548       2   
1             1             6           1           2         460       5   

   Grvl  Pave  
0     0     1  
1     0     1  

[2 rows x 26 columns]

### part e

In [13]:
from sklearn.preprocessing import StandardScaler
import numpy as np
train_x_d= train_x_d.astype(float) #converts any value of train_x_d to the float
data_norm = train_x_d.copy() #Has train data frames combined to form single data frame
normalizer = StandardScaler() #StandardScaler function for standardization
data_array = normalizer.fit_transform(data_norm) #Fit to data, then transform it
train_x_e= pd.DataFrame(data_array,columns = data_norm.columns).set_index(data_norm.index) #creating new data frame for train_x_e

In [14]:
train_x_e.head(2)

MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  MasVnrArea  \
0    0.073872    -0.235351 -0.196474     0.632900    -0.529618     0.46221   
1   -0.873204     0.475965 -0.095659    -0.090414     2.177118    -0.57897   

   BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF    ...     HalfBath  \
0    0.589782  -0.939672    -0.486827 -0.802481    ...     1.230454   
1    1.204925  -0.638291     0.475863  0.280104    ...    -0.773542   

   BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  \
0      0.178216     -0.208547      0.935889   -0.939129    0.316364   
1      0.178216     -0.208547     -0.307817    0.600426    0.316364   

   GarageArea    MoSold      Grvl      Pave  
0    0.357524 -1.601265 -0.063372  0.063372  
1   -0.063938 -0.485919 -0.063372  0.063372  

[2 rows x 26 columns]

## LINEAR REGRESSION TO PREDICT HOUSE PRICES

### part f

In [36]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression() #Linear regression model
lr_model.fit(train_x_e, train_y) #fitting model 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [37]:
from sklearn.metrics import mean_squared_error
predictions = lin_reg.predict(train_x_e) #for predictions 
lin_mse = mean_squared_error(train_y, predictions) #mean_squared_error for calculating MSE

### part g

In [38]:
from sklearn.model_selection import cross_val_score
train_mse_score = cross_val_score(lin_reg,train_x_e,train_y,scoring="neg_mean_squared_error", cv=5) #for calculating train MSE
print train_mse_score

[-9.70357599e+08 -7.50683854e+08 -1.66939254e+09 -1.46924370e+09
 -8.85671506e+08]


In [18]:
average_mse=train_mse_score.mean() #mean function for average mse
print average_mse

-1149069841.008595


### part h

In [19]:
csv_path_test = os.path.join(DATASET_PATH, "test.csv")
test_x=pd.read_csv(csv_path_test,usecols=range(25))
test_y=pd.read_csv(csv_path_test)
test_y=pd.Series(test_y.values[:, -1], name=test_y.columns[-1])
test_x=test_x.fillna(test_x["LotFrontage"].median())
one_hot_test=pd.get_dummies(test_x["Street"])
test_x=test_x.drop("Street",axis=1)
test_x=test_x.join(one_hot_test)
test_x= test_x.astype(float)
data_norm_test = test_x.copy() 
data_array_test = normalizer.fit_transform(data_norm_test)
test_x= pd.DataFrame(data_array_test,columns = data_norm_test.columns).set_index(data_norm_test.index)

In [20]:
test_x.head(2)

MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  MasVnrArea  \
0   -0.871178     0.173992  0.011886    -2.204028    -2.275158   -0.565763   
1   -0.635309    -0.411130 -0.825874    -0.755667     0.401498   -0.565763   

   BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF    ...     HalfBath  \
0   -0.908588  -1.300225    -2.217961 -0.563416    ...     -0.73653   
1   -0.908588   0.287067    -0.756925 -1.180596    ...     -0.73653   

   BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageCars  \
0     -1.088257     -0.218714     -1.547027   -0.978492    0.301860   
1     -1.088257     -0.218714     -1.547027   -0.978492   -1.020574   

   GarageArea    MoSold      Grvl      Pave  
0    0.249123  0.236471 -0.066082  0.066082  
1   -1.143224 -1.961040 -0.066082  0.066082  

[2 rows x 26 columns]

In [21]:
test_y.head(2)

0    82000
1    86000
Name: SalePrice, dtype: object

### part i 

In [39]:
lin_reg1 = LinearRegression()
lin_reg1.fit(test_x, test_y)
predicted_values=lin_reg1.predict(test_x) #prediction with linear regression model

In [23]:
print predicted_values[10:13] #writing predicted_values

[107497.14218337  88173.15945005 159379.7576981 ]


In [24]:
test_mse_score =cross_val_score(lin_reg1,test_x,test_y,scoring="neg_mean_squared_error", cv=5) #calculating test MSE 
print test_mse_score

[-1.40038409e+09 -3.43195233e+09 -1.15040816e+09 -6.48252332e+09
 -8.92243071e+08]


## CLASSIFICATION MODEL TO PREDICT HOUSE PRICE CATEGORY

### part j

In [25]:
  
labels_train_y={"label1":[],"label2":[],"label3":[],"label4":[],"label5":[]}
for y in train_y: #seperating SalePrice columns into labels and putting 1,2,3,4,5 according to conditions.
    if y<100000:
        labels_train_y["label1"].append(1)
    elif y>=100000 and y<200000: 
        labels_train_y["label2"].append(2)
    elif y>=200000 and y<300000:
        labels_train_y["label3"].append(3)
    elif y>=300000 and y<400000:
        labels_train_y["label4"].append(4)
    elif y>=400000:
        labels_train_y["label5"].append(5)
train_y_j=pd.DataFrame([(i, train_prices) for i,j in labels_train_y.items() for train_prices in j], 
                  columns=['Labels','SalePrice']) #extracting values from dict and creating dataframe for train_y_j and test_y_j
train_y_j=train_y_j["SalePrice"]
labels_test_y={"label1":[],"label2":[],"label3":[],"label4":[],"label5":[]}
for y in test_y:
    if y<100000:
        labels_test_y["label1"].append(1)
    elif y>=100000 and y<200000: 
        labels_test_y["label2"].append(2)
    elif y>=200000 and y<300000:
        labels_test_y["label3"].append(3)
    elif y>=300000 and y<400000:
        labels_test_y["label4"].append(4)
    elif y>=400000:
        labels_test_y["label5"].append(5)
test_y_j=pd.DataFrame([(i, test_prices) for i,j in labels_test_y.items() for test_prices in j], 
                  columns=['Labels','SalePrice'])
test_y_j=test_y_j["SalePrice"]



In [26]:
train_y_j.head(2)


0    1
1    1
Name: SalePrice, dtype: int64

In [27]:
test_y_j.head(2)

0    1
1    1
Name: SalePrice, dtype: int64

### part k

In [28]:
from sklearn import linear_model
from sklearn.linear_model import SGDClassifier
model=linear_model.SGDClassifier(max_iter=1000) #multiclass classification model with Stochastic Gradient Descent
model.fit(train_x_e, train_y_j) #fitting model


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=1000,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

### part l

In [29]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
scores=cross_val_score(model, train_x_e,train_y_j , cv=5) # calculating cros vallidation score
train_y_pred = cross_val_predict(model, train_x_e,train_y_j, cv=5) #prediction for accuracy,confusion matrix, f1 score recall and precision
accuracy=accuracy_score(train_y_j, train_y_pred) #calculating accuracy
confusion_matrix=confusion_matrix(train_y_j, train_y_pred)#calculating confusion matrix
recall=recall_score(train_y_j, train_y_pred, average='micro')#calculating recall
precision=precision_score(train_y_j, train_y_pred, average='micro')#calculating precision
f1 = f1_score(train_y_j, train_y_pred, average='micro')#calculating f1 score

In [30]:
print(confusion_matrix)
print("accuracy: {}\nprecision: {}\nrecall: {}\nf1: {}".format(accuracy,precision,recall,f1)) 

[[  0  75   2   0   0]
 [  2 605   6   0   1]
 [  2 213   2   3   1]
 [  0  67   0   0   0]
 [  0  21   0   0   0]]
accuracy: 0.607
precision: 0.607
recall: 0.607
f1: 0.607


### part m

In [31]:
predicted_values = model.predict(test_x) #predicting test_x with classification model

In [32]:
print(predicted_values[20:23])

[2 2 2]


In [33]:
from sklearn.metrics import confusion_matrix
accuracy=accuracy_score(test_y_j, predicted_values)#calculating accuracy
confusion_matrix=confusion_matrix(test_y_j, predicted_values.tolist())#calculating confusion matrix
recall=recall_score(test_y_j, predicted_values, average='micro') #calculating recall
precision=precision_score(test_y_j, predicted_values, average='micro') #calculating precision
f1 = f1_score(test_y_j,predicted_values, average='micro') #calculating f1 score

In [35]:
print(confusion_matrix)
print("accuracy: {}\nprecision: {}\nrecall: {}\nf1: {}".format(accuracy,precision,recall,f1)) 

[[  0  34   3   0   0]
 [  0 290   7   0   0]
 [  0  93   6   0   0]
 [  0  20   0   0   0]
 [  0   7   0   0   0]]
accuracy: 0.64347826087
precision: 0.64347826087
recall: 0.64347826087
f1: 0.64347826087
